#!/bin/bash
set -e
NAME=$1
cert_name="CA"
subj="/C=US/ST=California/L=Los Angeles/O=yourname.com/CN=$NAME"

if [[ $NAME == "" ]]; then
  echo "You must specify a name for the cert."
  exit 1
fi

if [[ -f CA/private/$NAME.key ]]; then
  echo "A cert with the name $NAME already exists. You must revoke this key if you want to make one with the same name."
  exit 1
fi

echo "k, I'm making a cert called $NAME"
openssl genrsa -out $cert_name/private/$NAME.key 2048
openssl req -new -subj "$subj" -key $cert_name/private/$NAME.key -out $cert_name/certs/$NAME.csr
openssl ca -batch -config openssl.cnf -extensions usr_cert -notext -md sha256 -in $cert_name/certs/$NAME.csr -out $cert_name/certs/$NAME.crt
cat $cert_name/certs/$NAME.crt $cert_name/private/$NAME.key > $cert_name/private/$NAME.pem
exit 0
